spring:
  data:
    mongodb:
      database: jiraTempo
      host: mongo
  main:
    web-application-type: reactive
  resources:
    static-locations: "file:/dist/"
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"


jiraTempo:
  tempoRefreshCron: "*/10 * * * * *"

